name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 允许推送构建结果

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库并拉取子模块
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive   # 自动拉取 themes/PaperMod
          fetch-depth: 0

      # 2️⃣ 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 3️⃣ 构建 Hugo
      - name: Build site
        run: hugo --minify

      # 4️⃣ 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
